In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dframe=pd.read_excel("EU_Real_Estate_Dataset.xlsx")

In [ ]:
dframe.head()

,property_id,listing_date,property_type,listing_type,address,city,country,bedrooms,bathrooms,square_meters,...,latitude,longitude,last_sold_price_eur,parking_spots,gym,swimming_pool,elevator,furnishing_status,energy_rating,floor_number
0,PROP-00001,2021-06-06,Townhouse,Sale,Paseo de la Castellana 122,Madrid,Spain,2,2.0,94.0,...,40.444365,-3.705707,203111.0,2,No,No,Yes,Semi-Furnished,C,NaN
1,PROP-00002,2024-06-29,Apartment,Sale,Rue de la Loi 35,Brussels,Belgium,2,1.0,85.0,...,50.902379,4.276731,297896.0,0,No,No,No,Unfurnished,B,6.0
2,PROP-00003,2022-02-18,Townhouse,Sale,Aleje Jerozolimskie 170,Warsaw,Poland,3,2.0,111.0,...,52.278988,21.022699,103127.0,1,No,No,No,Semi-Furnished,G,NaN
3,PROP-00004,2020-11-02,Townhouse,Sale,Prinsengracht 191,Amsterdam,Netherlands,3,3.0,115.0,...,52.335220,4.831571,478928.0,1,Yes,Yes,No,Unfurnished,E,NaN
4,PROP-00005,2021-04-04,Apartment,Sale,Potsdamer Platz 14,Berlin,Germany,3,1.0,100.0,...,52.598500,13.326092,178311.0,1,No,No,Yes,Unfurnished,E,9.0

In [ ]:
dframe.isna().sum()

property_id               0
listing_date              0
property_type             0
listing_type              0
address                   0
city                      0
country                   0
bedrooms                  0
bathrooms              1775
square_meters           247
year_built              241
sale_price_eur         2045
monthly_rent_eur       2955
price_per_sqm           247
days_on_market          248
latitude                  0
longitude                 0
last_sold_price_eur     585
parking_spots             0
gym                       0
swimming_pool             0
elevator                  0
furnishing_status      1775
energy_rating             0
floor_number           1168
dtype: int64

Financial Columns

In [ ]:
dframe['sale_price_eur'].fillna(0, inplace=True)
dframe['monthly_rent_eur'].fillna(0, inplace=True)

/tmp/ipykernel_4683/304235300.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['sale_price_eur'].fillna(0, inplace=True)
/tmp/ipykernel_4683/304235300.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['monthly_rent_eur'].fillna(0, inplace=True)

Because missing values represent different listing types (sale vs rent), so 0 indicates not applicable rather than missing data

In [ ]:
# Step 1: city + property_type
dframe['bathrooms'] = dframe.groupby(['city', 'property_type'])['bathrooms']\
                    .transform(lambda x: x.fillna(x.median()))
# Step 2: city only
dframe['bathrooms'] = dframe.groupby('city')['bathrooms']\
                    .transform(lambda x: x.fillna(x.median()))
# Step 3: global median
dframe['bathrooms'].fillna(dframe['bathrooms'].median(), inplace=True)

/tmp/ipykernel_4683/1478217470.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['bathrooms'].fillna(dframe['bathrooms'].median(), inplace=True)

In [ ]:
#square meters
dframe['square_meters'] = dframe.groupby(['city','property_type'])['square_meters']\
                        .transform(lambda x: x.fillna(x.median()))

dframe['square_meters'].fillna(dframe['square_meters'].median(), inplace=True)

/tmp/ipykernel_4683/3251721613.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['square_meters'].fillna(dframe['square_meters'].median(), inplace=True)

In [ ]:
#year built
dframe['year_built'].fillna(dframe['year_built'].median(), inplace=True)

In [ ]:
#floor_number
dframe['floor_number'] = dframe.groupby(['city','property_type'])['floor_number']\
                       .transform(lambda x: x.fillna(x.median()))

dframe['floor_number'].fillna(0, inplace=True)

/tmp/ipykernel_4683/1190038110.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['floor_number'].fillna(0, inplace=True)

In [ ]:
#datys_on_market
dframe['days_on_market'] = dframe.groupby(['property_type','city'])['days_on_market']\
                         .transform(lambda x: x.fillna(x.median()))
dframe['days_on_market'] = dframe.groupby('property_type')['days_on_market']\
                         .transform(lambda x: x.fillna(x.median()))
dframe['days_on_market'].fillna(dframe['days_on_market'].median(), inplace=True)

/tmp/ipykernel_4683/3747280769.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['days_on_market'].fillna(dframe['days_on_market'].median(), inplace=True)

In [ ]:
#price_per_sqm
dframe['price_per_sqm'] = dframe['sale_price_eur'] / dframe['square_meters']

In [ ]:
#furnishing_status
dframe['furnishing_status'].fillna("Unknown", inplace=True)

/tmp/ipykernel_4683/1317474501.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['furnishing_status'].fillna("Unknown", inplace=True)

In [ ]:
#last_sold_price_eur
dframe['last_sold_price_eur'].fillna(dframe['last_sold_price_eur'].median(), inplace=True)

/tmp/ipykernel_4683/2789599436.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dframe['last_sold_price_eur'].fillna(dframe['last_sold_price_eur'].median(), inplace=True)

In [ ]:
dframe.isna().sum()

property_id            0
listing_date           0
property_type          0
listing_type           0
address                0
city                   0
country                0
bedrooms               0
bathrooms              0
square_meters          0
year_built             0
sale_price_eur         0
monthly_rent_eur       0
price_per_sqm          0
days_on_market         0
latitude               0
longitude              0
last_sold_price_eur    0
parking_spots          0
gym                    0
swimming_pool          0
elevator               0
furnishing_status      0
energy_rating          0
floor_number           0
dtype: int64

In [ ]:
#check the quality
dframe[['sale_price_eur','monthly_rent_eur']].describe()

       sale_price_eur  monthly_rent_eur
count    5.000000e+03       5000.000000
mean     6.218505e+05       1497.016400
std      1.103730e+06       3094.800377
min      0.000000e+00          0.000000
25%      0.000000e+00          0.000000
50%      2.776370e+05          0.000000
75%      7.761555e+05       1931.250000
max      1.328730e+07      47411.000000

In [ ]:
dframe.groupby('listing_type')[['sale_price_eur','monthly_rent_eur']].mean()

              sale_price_eur  monthly_rent_eur
listing_type
Rental          0.000000e+00       3660.186797
Sale            1.052201e+06          0.000000

In [ ]:
dframe[['bathrooms','square_meters','price_per_sqm']].describe()

         bathrooms  square_meters  price_per_sqm
count  5000.000000     5000.00000    5000.000000
mean      1.813000      182.63290    3102.207663
std       0.560798      136.49081    3532.429669
min       1.000000       30.00000       0.000000
25%       1.000000       98.00000       0.000000
50%       2.000000      139.00000    2700.086295
75%       2.000000      219.00000    4986.640143
max       4.000000     1000.00000   55047.475687

In [ ]:
dframe.sample(5)

,property_id,listing_date,property_type,listing_type,address,city,country,bedrooms,bathrooms,square_meters,...,latitude,longitude,last_sold_price_eur,parking_spots,gym,swimming_pool,elevator,furnishing_status,energy_rating,floor_number
1695,PROP-01696,2021-09-26,Warehouse,Sale,Rue du Faubourg Saint-Honoré 160,Paris,France,0,2.0,147.0,...,48.886579,2.377391,1125370.0,5,No,No,No,Unknown,D,4.0
32,PROP-00033,2024-09-28,Townhouse,Sale,Boulevard Haussmann 196,Paris,France,2,2.0,73.0,...,48.878459,2.305062,436482.0,1,No,No,Yes,Unfurnished,E,0.0
1230,PROP-01231,2024-01-01,Villa,Sale,Pařížská 179,Prague,Czech Republic,4,2.0,125.0,...,50.147749,14.427752,436482.0,1,No,No,No,Unfurnished,D,0.0
4793,PROP-04794,2021-10-27,Apartment,Sale,Calle Serrano 57,Madrid,Spain,5,2.0,161.0,...,40.350822,-3.647071,430026.0,1,No,No,Yes,Unfurnished,E,8.0
2158,PROP-02159,2024-11-25,Retail,Rental,Via Condotti 116,Rome,Italy,0,2.0,129.0,...,41.880408,12.429950,469892.0,0,No,No,No,Unknown,E,9.0

In [ ]:
dframe.duplicated().sum()

np.int64(0)

In [ ]:
#outliers
cols = [
    'sale_price_eur',
    'monthly_rent_eur',
    'square_meters',
    'price_per_sqm',
    'bathrooms',
    'days_on_market'
]

for col in cols:
    Q1 = dframe[col].quantile(0.25)
    Q3 = dframe[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    print(col, "outliers:", dframe[(dframe[col] < lower) | (dframe[col] > upper)].shape[0])

sale_price_eur outliers: 369
monthly_rent_eur outliers: 435
square_meters outliers: 377
price_per_sqm outliers: 65
bathrooms outliers: 61
days_on_market outliers: 0

In [ ]:
#handling
Q1 = dframe['sale_price_eur'].quantile(0.25)
Q3 = dframe['sale_price_eur'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

dframe['sale_price_eur'] = dframe['sale_price_eur'].clip(lower, upper)

In [ ]:
Q1 = dframe['monthly_rent_eur'].quantile(0.25)
Q3 = dframe['monthly_rent_eur'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

dframe['monthly_rent_eur'] = dframe['monthly_rent_eur'].clip(lower, upper)

In [ ]:
Q1 = dframe['square_meters'].quantile(0.25)
Q3 = dframe['square_meters'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

dframe['square_meters'] = dframe['square_meters'].clip(lower, upper)

In [ ]:
dframe['bathrooms'].describe()

count    5000.000000
mean        1.813000
std         0.560798
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         4.000000
Name: bathrooms, dtype: float64

** SUMMARY OF DATA CLEANING PROCESS **
- Loaded the European real estate dataset and performed initial exploration:
  • Checked data types, missing values, and overall structure.
  • Identified key features such as pricing, property characteristics, and location data.

- Handled missing values using appropriate strategies:
  • Financial columns (sale_price_eur, monthly_rent_eur) filled with 0 to represent non-applicable listings (sale vs rent).
  • Numerical columns (bathrooms, square_meters, year_built, floor_number, etc.) imputed using median and group-based methods (city, property_type, bedrooms).
  • Categorical column (furnishing_status) filled with "Unknown".

- Applied feature-aware imputation:
  • Used hierarchical grouping (city, property_type, bedrooms) to preserve real-world patterns.
  • Avoided overly granular grouping such as latitude/longitude.

- Ensured data consistency:
  • Recalculated price_per_sqm from sale_price_eur and square_meters.
  • Verified logical consistency across related features.

- Checked for duplicates:
  • Verified both exact duplicates and duplicates based on property_id.
  • No significant duplicate issues found.

- Performed outlier detection using the IQR method:
  • Identified outliers in pricing and size-related columns.
  • Recognized that many outliers represent real-world variation (e.g., luxury properties).

- Applied outlier handling:
  • Used capping (winsorization) for:
      - sale_price_eur
      - monthly_rent_eur
      - square_meters
  • Retained realistic extreme values to avoid data loss.
  • No action needed for bathrooms and days_on_market as values were within reasonable ranges.

- Final validation:
  • Confirmed no missing values remain.
  • Ensured data is clean, consistent, and analysis-ready.

- Outcome:
  Prepared a high-quality dataset suitable for SQL-based analysis and Power BI visualization.

In [44]:
dframe.to_csv("clean_data.csv", index=False)

In [45]:
from google.colab import files
files.download("clean_data.csv")